# Generated by Django 4.2.29 on 2026-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        choices=[("python", "Python"), ("c", "C"), ("java", "Java")],
                        max_length=20,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[("python", "Python"), ("c", "C"), ("java", "Java")],
                        max_length=20,
                    ),
                ),
                ("input_code", models.TextField()),
                ("output_code", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
