# Generated by Django 4.2.29 on 2026-03-07 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("c", "C"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("c", "C"),
                            ("java", "Java"),
                            ("javascript", "JavaScript"),
                            ("cpp", "C++"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_code", models.TextField()),
                ("output_code", models.TextField()),
                ("engine", models.CharField(default="ai", max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="conversionhistory",
            name="source_language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("c", "C"),
                    ("java", "Java"),
                    ("javascript", "JavaScript"),
                    ("cpp", "C++"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversionhistory",
            name="target_language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("c", "C"),
                    ("java", "Java"),
                    ("javascript", "JavaScript"),
                    ("cpp", "C++"),
                ],
                max_length=20,
            ),
        ),
    ]
