# Generated by Django 4.2.29 on 2026-03-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_quiz_quizquestion_quizoption_quizattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizoption",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
